### PR TITLE
Feature/auto complete commands

### PR DESCRIPTION
**Pull request by ambid17**
this could still be cleaned up a bit, it doesn't feel quite there

### CODE REVIEW

**Review by FuhrmannMaciej — COMMENTED** [review]
needs small fixing, Sabien said he's gonna finish it tonight :)

**Review by FuhrmannMaciej — CHANGES_REQUESTED** [review]
pressing tab without typing anything throws ArgumentOutOfRangeException, also when we time some random stuff and then try to use a command cache only works on the latest command can't go back with cache to the previous ones

**Review by FuhrmannMaciej — CHANGES_REQUESTED** [review]
tab is not throwing that error now, added a video to discord about the other thing ;)

**Review by FuhrmannMaciej — DISMISSED** [review]
works great!

**Review by FuhrmannMaciej — APPROVED** [review]
works just perfect!

**Review by 0xLeif — APPROVED** [review]

**Pull request merged**
